version: '3.8'

services:
  job-pipeline:
    build: .
    image: market-analysis:latest
    container_name: market-analysis-test
    env_file:
      - .env
    environment:
      # Only AWS credentials needed for secrets fetch
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: ["--preset", "test_page_list", "--name", "test_run"]


